server:
  port: 80
spring:
  datasource:
    #   数据库基本配置
    url: jdbc:mysql://localhost:3306/pay?useUnicode=true&charaterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    db-type: com.alibaba.druid.pool.DruidDataSource
    #   druid源配置
    druid:
      #   配置初始化线程大小，最小线程池
      initial-size: 5
      min-idle: 1
      #   CPU核数+1  可以大写，但最好不要超过20
      max-active: 10
      #   最大等待时间
      max-wait: 60000
      time-between-eviction-runs-millis: 6000
      #   配置一个连接在池中的最大时间
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1
      test-while-idle: true
      #   设置从连接池获取连接是否检测连接有效性
      test-on-borrow: true
      #   设置从连接池归还连接是否检测连接有效性
      test-on-return: true
      #   可以支持PSCache（提升写入、查询效率）
      pool-prepared-statements: true
      #   配置监控统计拦截的filters，去掉后监控界面sql无法统计，wall用于防火墙
      filter: stat,wall,log4j
      #   保持长连接
      keep-alive: true
      max-pool-prepared-statement-per-connection-size: 20
      use-global-data-source-stat: true
      connect-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMills=500
  redis:
    host: 127.0.0.1
    password: root
    port: 6379